-- Script complet pour recréer les vues après suppression en cascade

-- 1. D'abord v_mailles_with_location_counts (vue originale complète)
CREATE OR REPLACE VIEW atlas.v_mailles_with_location_counts AS
WITH location_counts AS (
    SELECT m.code,
        count(DISTINCT s.id) FILTER (WHERE (s.location_mode = ANY (ARRAY['exact'::text, 'gps'::text, 'manual'::text]))) AS n_sondages_exact,
        count(DISTINCT s.id) FILTER (WHERE (s.location_mode = ANY (ARRAY['adm_random_cell'::text, 'adm3'::text, 'adm2'::text, 'adm1'::text, 'random'::text]))) AS n_sondages_random
    FROM atlas.mailles m
    LEFT JOIN atlas.sondages s ON (st_contains(m.geom, st_transform(s.geom, 25231)) AND (s.deleted_at IS NULL) AND (s.geom IS NOT NULL))
    GROUP BY m.code
)
SELECT mv.id,
    mv.code,
    mv.geom,
    st_transform(mv.geom, 4326) as geom_4326,
    st_simplify(mv.geom, 100) as geom_simplified,
    NULL as adm1_name,
    mv.adm2_name,
    NULL as adm3_name,
    0 as n_sondages,
    0 as n_echantillons,
    0 as n_essais_atterberg,
    0 as n_essais_vbs,
    0 as n_essais_proctor,
    0 as n_essais_gonflement,
    0 as n_essais_granulo,
    0 as n_essais_classif,
    0 as n_essais_total,
    0 as depth_min_m,
    0 as depth_max_m,
    0 as depth_mean_m,
    NULL::numeric as wl_avg,
    NULL::numeric as wl_min,
    NULL::numeric as wl_max,
    NULL::numeric as wp_avg,
    NULL::numeric as wp_min,
    NULL::numeric as wp_max,
    NULL::numeric as ip_avg,
    NULL::numeric as ip_min,
    NULL::numeric as ip_max,
    NULL::numeric as ip_stddev,
    NULL::numeric as vbs_avg,
    NULL::numeric as vbs_min,
    NULL::numeric as vbs_max,
    NULL::numeric as vbs_stddev,
    0 as n_vbs_insensible,
    0 as n_vbs_peu_sensible,
    0 as n_vbs_sensible,
    0 as n_vbs_moyen_argileux,
    0 as n_vbs_argileux,
    0 as n_vbs_tres_argileux,
    NULL::numeric as gamma_d_max_avg,
    NULL::numeric as gamma_d_max_min,
    NULL::numeric as gamma_d_max_max,
    NULL::numeric as w_opt_avg,
    NULL::numeric as w_opt_min,
    NULL::numeric as w_opt_max,
    NULL::numeric as eg_avg,
    NULL::numeric as eg_min,
    NULL::numeric as eg_max,
    NULL::numeric as eg_stddev,
    0 as n_eg_negligeable,
    0 as n_eg_faible,
    0 as n_eg_moyen,
    0 as n_eg_fort,
    0 as n_eg_tres_fort,
    NULL::numeric as passant_80um_avg,
    NULL::numeric as passant_80um_min,
    NULL::numeric as passant_80um_max,
    NULL::numeric as passant_2mm_avg,
    NULL::numeric as passant_2mm_min,
    NULL::numeric as passant_2mm_max,
    NULL::numeric as passant_20mm_avg,
    0 as n_classif_hrb,
    0 as n_classif_unified,
    0 as n_classif_amessefe,
    false as has_data,
    false as has_exact_location,
    false as has_random_location,
    0 as n_sondages_exact,
    0 as n_sondages_random
FROM atlas.mailles mv
LEFT JOIN location_counts lc ON lc.code = mv.code;

-- 2. mv_mailles_geotech
CREATE MATERIALIZED VIEW atlas.mv_mailles_geotech AS
SELECT * FROM atlas.v_mailles_with_location_counts;

REFRESH MATERIALIZED VIEW atlas.mv_mailles_geotech;

-- 3. mailles_geotechnique_stats_wgs84
CREATE VIEW atlas.mailles_geotechnique_stats_wgs84 AS
SELECT 
    mv.id,
    mv.code,
    mv.geom,
    mv.geom_4326,
    mv.geom_simplified,
    mv.adm1_name,
    mv.adm2_name,
    mv.adm3_name,
    COALESCE(mv.n_sondages, 0) as n_sondages,
    COALESCE(mv.n_sondages_exact, 0) as n_sondages_exact,
    COALESCE(mv.n_sondages_random, 0) as n_sondages_random,
    COALESCE(mv.n_echantillons, 0) as n_echantillons,
    COALESCE(mv.n_essais_total, 0) as n_essais_geo,
    COALESCE(mv.n_essais_total, 0) as n_essais_total,
    mv.has_data,
    mv.has_exact_location,
    mv.has_random_location,
    mv.wl_avg,
    mv.wp_avg,
    mv.ip_avg,
    mv.ip_stddev,
    mv.ip_min,
    mv.ip_max,
    mv.vbs_avg,
    mv.vbs_stddev,
    mv.vbs_min,
    mv.vbs_max,
    mv.gamma_d_max_avg,
    mv.gamma_d_max_min as gamma_d_max_stddev,
    mv.w_opt_avg,
    mv.w_opt_min as w_opt_stddev,
    mv.eg_avg,
    mv.eg_stddev,
    mv.eg_min,
    mv.eg_max,
    mv.passant_80um_avg,
    mv.passant_2mm_avg,
    mv.passant_20mm_avg,
    COALESCE(mv.n_vbs_insensible, 0) as n_vbs_insensible,
    COALESCE(mv.n_vbs_peu_sensible, 0) as n_vbs_peu_sensible,
    COALESCE(mv.n_vbs_sensible, 0) as n_vbs_sensible,
    COALESCE(mv.n_vbs_moyen_argileux, 0) as n_vbs_moyen_argileux,
    COALESCE(mv.n_vbs_argileux, 0) as n_vbs_argileux,
    COALESCE(mv.n_vbs_tres_argileux, 0) as n_vbs_tres_argileux,
    COALESCE(mv.n_eg_negligeable, 0) as n_eg_negligeable,
    COALESCE(mv.n_eg_faible, 0) as n_eg_faible,
    COALESCE(mv.n_eg_moyen, 0) as n_eg_moyen,
    COALESCE(mv.n_eg_fort, 0) as n_eg_fort,
    COALESCE(mv.n_eg_tres_fort, 0) as n_eg_tres_fort,
    m.vbs_rk_h1,
    m.vbs_rk_h2,
    m.vbs_rk_h3,
    m.ip_rk_h1,
    m.ip_rk_h2,
    m.ip_rk_h3,
    m.wl_rk_h1,
    m.wl_rk_h2,
    m.wl_rk_h3,
    m.wp_rk_h1,
    m.wp_rk_h2,
    m.wp_rk_h3,
    m.eg_rk_h1,
    m.eg_rk_h2,
    m.eg_rk_h3
FROM atlas.mv_mailles_geotech mv
LEFT JOIN atlas.mailles m ON m.code = mv.code;

-- Vérification
SELECT 'total' as test, COUNT(*) as cnt FROM atlas.mailles_geotechnique_stats_wgs84
UNION ALL
SELECT 'vbs_rk_h1', COUNT(vbs_rk_h1) FROM atlas.mailles_geotechnique_stats_wgs84;