-- Recréer la vue mailles_geotechnique_stats_wgs84 avec les colonnes RK
-- Utilise mv_mailles_geotech comme base et joint avec mailles pour les RK

CREATE OR REPLACE VIEW atlas.mailles_geotechnique_stats_wgs84 AS
SELECT 
    mv.id,
    mv.code,
    mv.geom,
    mv.geom_4326,
    mv.geom_simplified,
    mv.adm1_name,
    mv.adm2_name,
    mv.adm3_name,
    mv.n_sondages,
    mv.n_sondages_exact,
    mv.n_sondages_random,
    mv.n_echantillons,
    mv.n_essais_total as n_essais_geo,
    mv.has_data,
    mv.has_exact_location,
    mv.has_random_location,
    mv.wl_avg,
    mv.wp_avg,
    mv.ip_avg,
    mv.ip_stddev,
    mv.ip_min,
    mv.ip_max,
    mv.vbs_avg,
    mv.vbs_stddev,
    mv.vbs_min,
    mv.vbs_max,
    mv.gamma_d_max_avg,
    mv.gamma_d_max_min as gamma_d_max_stddev,
    mv.w_opt_avg,
    mv.w_opt_min as w_opt_stddev,
    mv.eg_avg,
    mv.eg_stddev,
    mv.eg_min,
    mv.eg_max,
    mv.passant_80um_avg,
    mv.passant_2mm_avg,
    mv.passant_20mm_avg,
    mv.n_vbs_insensible,
    mv.n_vbs_peu_sensible,
    mv.n_vbs_sensible,
    mv.n_vbs_moyen_argileux,
    mv.n_vbs_argileux,
    mv.n_vbs_tres_argileux,
    mv.n_eg_negligeable,
    mv.n_eg_faible,
    mv.n_eg_moyen,
    mv.n_eg_fort,
    mv.n_eg_tres_fort,
    -- Colonnes RK depuis mailles
    m.vbs_rk_h1,
    m.vbs_rk_h2,
    m.vbs_rk_h3,
    m.ip_rk_h1,
    m.ip_rk_h2,
    m.ip_rk_h3,
    m.wl_rk_h1,
    m.wl_rk_h2,
    m.wl_rk_h3,
    m.wp_rk_h1,
    m.wp_rk_h2,
    m.wp_rk_h3,
    m.eg_rk_h1,
    m.eg_rk_h2,
    m.eg_rk_h3
FROM atlas.mv_mailles_geotech mv
LEFT JOIN atlas.mailles m ON m.code = mv.code;

-- Vérification
SELECT COUNT(*) as total FROM atlas.mailles_geotechnique_stats_wgs84;
SELECT COUNT(vbs_rk_h1) as vbs_rk_count FROM atlas.mailles_geotechnique_stats_wgs84;