-- Recréer la vue mailles_geotechnique_stats_wgs84 avec les colonnes RK
-- Elle est utilisée par l'API thematic pour lire les paramètres

CREATE OR REPLACE VIEW atlas.mailles_geotechnique_stats_wgs84 AS
SELECT 
    m.id,
    m.code,
    m.geom AS geom,
    NULL AS geom_simplified,
    m.adm1_name,
    m.adm2_name,
    m.adm3_name,
    0 as n_sondages,
    0 as n_sondages_exact,
    0 as n_sondages_random,
    0 as n_echantillons,
    0 as n_essais_geo,
    false as has_data,
    false as has_exact_location,
    false as has_random_location,
    NULL as wl_avg,
    NULL as wp_avg,
    NULL as ip_avg,
    NULL as ip_stddev,
    NULL as ip_min,
    NULL as ip_max,
    NULL as vbs_avg,
    NULL as vbs_stddev,
    NULL as vbs_min,
    NULL as vbs_max,
    NULL as gamma_d_max_avg,
    NULL as gamma_d_max_stddev,
    NULL as w_opt_avg,
    NULL as w_opt_stddev,
    NULL as eg_avg,
    NULL as eg_stddev,
    NULL as eg_min,
    NULL as eg_max,
    NULL as passant_80um_avg,
    NULL as passant_2mm_avg,
    NULL as passant_20mm_avg,
    0 as n_vbs_insensible,
    0 as n_vbs_peu_sensible,
    0 as n_vbs_sensible,
    0 as n_vbs_moyen_argileux,
    0 as n_vbs_argileux,
    0 as n_vbs_tres_argileux,
    0 as n_eg_negligeable,
    0 as n_eg_faible,
    0 as n_eg_moyen,
    0 as n_eg_fort,
    0 as n_eg_tres_fort,
    -- Colonnes RK
    m.vbs_rk_h1,
    m.vbs_rk_h2,
    m.vbs_rk_h3,
    m.ip_rk_h1,
    m.ip_rk_h2,
    m.ip_rk_h3,
    m.wl_rk_h1,
    m.wl_rk_h2,
    m.wl_rk_h3,
    m.wp_rk_h1,
    m.wp_rk_h2,
    m.wp_rk_h3,
    m.eg_rk_h1,
    m.eg_rk_h2,
    m.eg_rk_h3
FROM atlas.mailles m;

-- Vérification
SELECT COUNT(*) as total FROM atlas.mailles_geotechnique_stats_wgs84;
SELECT COUNT(vbs_rk_h1) as vbs_rk_count FROM atlas.mailles_geotechnique_stats_wgs84;